const countriesList = [
  //   { id: 7, name: "Argentina" },
  //   { id: 9, name: "Australia" },
  //   { id: 10, name: "Austria" },
  //   { id: 17, name: "Belgium" },
  //   { id: 24, name: "Brazil" },
  //   { id: 43, name: "Croatia" },
  //   { id: 46, name: "Czech Republic" },
  { id: 60, name: "France" },
  { id: 64, name: "Germany" },
  //   { id: 66, name: "Greece" },
  //   { id: 74, name: "Hungary" },
  //   { id: 75, name: "Iceland" },
  //   { id: 76, name: "India" },
  //   { id: 80, name: "Ireland" },
  { id: 82, name: "Italy" },
  //   { id: 87, name: "Kenya" },
  //   { id: 118, name: "Marocco" },
  { id: 124, name: "Netherlands" },
  //   { id: 136, name: "Peru" },
  //   { id: 138, name: "Poland" },
  //   { id: 139, name: "Portugal" },
  //   { id: 140, name: "Qatar" },
  { id: 142, name: "Russia" },
  //   { id: 160, name: "South Africa" },
  { id: 161, name: "Spain" },
  //   { id: 167, name: "Switzerland" },
  //   { id: 177, name: "Turkey" },
  { id: 182, name: "United Arab Emirates" },
  { id: 183, name: "United Kingdom" },
  { id: 184, name: "United States of America" },
];

export { countriesList };
